Events and forums for R users
=============================


From RStudio 
-------------------------

### https://resources.rstudio.com.

Webinars



### RStudio Community Meetup

Another great meetup opportunity:

<https://www.meetup.com/RStudio-Enterprise-Community-Meetup>

NB: you may be able to access it from GC network.

Each meetup is dedicated to a specific topic, following which they post many Q&A at <https://community.rstudio.com/>

R blogs
-------

- https://rpubs.com


R conferences
-------------

(from <https://rviews.rstudio.com/2021/03/03/2021-r-conferences>)

-   Cascadia RConf 2021 (June 4 - 5), a jewel of a regional R conference for its first three years, was canceled in 2020. It is back this year as a virtual event. The Call for Presentations is open.

-   useR! 2021 (July 5 - 9) has an outstanding lineup of keynote speakers. The program is very likely to make US based attendees night-owls

-   EARL Conference 2021 (September 6 - 10), the premier R in industry event, will be online this year. The call for abstracts is already open.

Related journals:
----------------

This is where you can submit or present your data science work.

-   <https://peerj.com/articles/?q=data>

-   <https://earlconf.com/#about>: The Enterprise Applications of the R Language Conference (EARL)

-   <https://odsc.com/boston/>: Data Science Conference & Expo

-   <https://journals.plos.org/plosone/search?filterJournals=PLoSONE&q=data+science> (research by the US Department of Homeland Security is published there)

See also (from <http://charteredabs.org/academic-journal-guide-2015-view/> (Rank 4-3))

-   Management Science

-   IEEE Transactions on Systems, Man, and Cybernetics: Systems (formerly "IEEE Transactions on Systems, Man and Cybernetics - Part A: Systems and Humans")

-   Annals of Operations Research

-   IEEE Transactions on Cybernetics (formerly "IEEE Transactions on Systems Man and Cybernetics Part C (Applications and Reviews)")

-   INFORMS Journal on Computing OR Spectrum

-   Transportation Science

Computational Statistics & Data Analysis

### Academic Journals:

-   Operations Research (Informs): <https://pubsonline.informs.org/journal/opre> <https://www.scirp.org/journal/jdaip/> - Journal of Data Analysis and Information Processing

RElated conferences
-----------

### Non-academic

### Academic Conferences:

-   Canadian AI Conference - <https://www.caiac.ca/en/conferences>

- Otheer AI conferences

### IEEE Conferences

-   IEEE BigData
-   IEEE International Conference on Technologies for Homeland Security HST




Related communities in GC
-------------------------

Roughly sorted by the level of group activity

### GCConnex (GC only):

-   <https://gcconnex.gc.ca/groups/profile/5394852/data-science-goc>
-   <https://gcconnex.gc.ca/groups/profile/56632124/statcan-data-science-communities-of-practice-hub>
-   <https://gcconnex.gc.ca/groups/profile/53857931/applied-machine-learning-ml-for-text-analysis-community-of-practice-cop>
-   <https://gcconnex.gc.ca/groups/profile/22346843/big-data-community>
-   <https://gcconnex.gc.ca/groups/profile/39621554/data-visualization-resources>
-   <https://gcconnex.gc.ca/groups/profile/24345174/data-visualization>
-   <https://gcconnex.gc.ca/groups/profile/47035648/machine-learning-in-remote-sensing-cop>
-   <https://gcconnex.gc.ca/groups/profile/24825105/data-analytics-coalition>
-   <https://gcconnex.gc.ca/groups/profile/47035648/machine-learning-in-remote-sensing-cop>
-   <https://gcconnex.gc.ca/groups/profile/19758048/analytics-mining-and-hypothesis-testing>
-   <https://gcconnex.gc.ca/groups/profile/62219803/artificial-intelligence-and-data-science-group>
-   <https://gcconnex.gc.ca/groups/profile/30787891/digital-academy>
-   <https://gcconnex.gc.ca/groups/profile/36236376/candev-data-challenge->
-   <https://gcconnex.gc.ca/groups/profile/4474153/data-analytics-working-group-dawg>
-   <https://gcconnex.gc.ca/groups/profile/34024870/welcome-to-r-canadian-government> (not active)

### GCcode (GC only):

-   <https://gccode.ssc-spc.gc.ca/r4gc>
-   <https://gccode.ssc-spc.gc.ca/DSCV>

### GCcollab (public with login):

-   <https://gccollab.ca/groups/profile/778815/eneccc-network-of-experts-and-researchers-in-data-science-nerdsfrlabo-de-donnu00e9es>
-   <https://gccollab.ca/groups/profile/3465987/enswam-support-for-wildlife-analysis-and-monitoringfr>
-   <https://gccollab.ca/groups/profile/18873/enopen-governmentfrgouvernement-ouvert>
-   <https://gccollab.ca/groups/profile/7071541/endata-engineering-challenges-and-solutions> (\#GCData2021 conference workshop)

More GCcollab groups are listed at <https://wiki.gccollab.ca/The_Square/GCcollab_Groups>

### GCwiki (public):

-   <https://wiki.gccollab.ca/The_Square/Data_Science>

### GitHub (public):

-   <https://github.com/open-data>
-   <https://github.com/canada-ca>
-   <https://github.com/PatLittle>

### Other Canada groups

-   <https://code.open.canada.ca/en/open-source-softwares.html>

<!-- # Open R codes for GC: on GCcode and GitHub -->