

# R Markdown for literate programming and automated reports

This discussion thread is for gathering knowledgebase related to R Markdown: https://rmarkdown.rstudio.com/

It can be used to generate reports, slides, websites, dashboards, shiny app, books, emails.
It is the tools allows you to do [literate programming](https://en.wikipedia.org/wiki/Literate_programming), which -- as defined by Donald Knuth - is the type of programming  where human language is combined with  computer language, making the code much easier understood by  your colleagues and yourself and  coding much more fun.

## Resources

Main reference: https://bookdown.org/yihui/rmarkdown/



A couple of great webinars from RStudio folks on advanced use of R Markdown - with lots of source codes:


- https://www.rstudio.com/resources/webinars/rethink-reporting-with-automation/
- https://www.rstudio.com/resources/webinars/sharing-on-short-notice-how-to-get-your-materials-online-with-r-markdown/


Business Reports with R Markdown:
https://github.com/cderv/meetup-2021-rmd-business-report


R Markdown Taxonomy:
https://github.com/jthomasmock/penguin-project




## Automated generation of multiple PDF files

Question:
"Can we automatically generate multiple PDF files using R RMarkdown? E.g. 20 report cards in PDF format, each showing results for 50 different parameters of the analysis?"

Answer: "Absolutely!" - This is what RMarkdown is developed for.



Here's a tiny  R script example showing how to do it.

```{r eval=FALSE, include=FALSE}

# report_generator.R

mvndr_nm <- c('name1', 'name2', 'name3', 'name4', 'name5', 'name6')
mvndr_nbr<- c('60031167', '60688509', '60074051', '60148060', '60086898', '60080204')

for (i in seq_along(mvndr_nm)) {
  rmarkdown::render("C:/Users/santi/Documents/R Scripts/Export_Data_CSV.Rmd",
                    output_file = sprintf("MVNDR_%s.html", mvndr_nbr[i]),
                    params = list(MVNDR_NBR = mvndr_nbr[i], MVNDR_NM = mvndr_nm[i]))
}

# Export_Data_CSV.Rmd
# (remove # below)

#---
#title: "`r params$MVNDR_NBR`"
#author: "Santiago Canon"
#date: "5/26/2021"
#output:
#  html_document:
#    highlight: monochrome
#    theme: flatly
#params:
#  MVNDR_NBR: NA
#  MVNDR_NM: NA
#---

#<font size="4"> This document will provide a summary of "`r params$MVNDR_NM`" performance within in QC: </font>
```

Source:
- https://stackoverflow.com/questions/67739377/passing-multiple-parameters-in-rmarkdown-document
- https://stackoverflow.com/questions/60203785/using-multiple-params-in-rmarkdown-yaml-fields





<!-- # (PART) Specialized topics {.unnumbered} -->



<!-- (and other languages/tools) -->



# ggplot2 and its extensions for data visualization


Many come to R (from Python and other languages/ systems) mainly because of the advanced data visualization capabilities it offers. There are many of those, as are the resources. Share your recommendations and examples here.



## Resources

See: https://github.com/IVI-M/R-Ottawa/blob/master/resources.md

Introduction to ggplot2

How to customize ggplot2

Top 50 ggplot2 visualizations

ggplot2 quick reference sheet

ggplot2 quick reference for colour names

Modifying components of theme() in ggplot2

Colours in ggplot2, including colour-blind friendly palette

Package for colour manipulation, including visualizing the effects of colour-blindness on colour palettes. https://cran.r-project.org/package=prismatic

Dmitry Gorodnichy's avatar
By Dmitry Gorodnichy 2021-04-08 22:15Edit the discussion reply by Dmitry GorodnichyDelete the discussion reply by Dmitry GorodnichyLike the discussion reply by Dmitry Gorodnichy
bookdown.org books on advanced visualization with ggplot and its extensions

https://serialmentor.com/dataviz/ - https://github.com/clauswilke/dataviz.
Fundamentals of Data Visualization. Claus O. Wilke
https://github.com/jjallaire/dataviz-r


OpenSDP Dataviz Tutorial (R)


### Plotly + R Shiny

https://socviz.co/ -
Data Visualization. A practical introduction
https://r-graphics.org/
R Graphics Cookbook, 2nd edition. Winston Chang. 2019-12-19
with Plotly in R

Intro to Animations | R | Plotly - https://plotly.com/r/animations/
https://plotly-r.com/index.html
https://plot.ly/r/animations/




# Shiny for Interactive Data Visualization, Analysis and Web App development


This discussion thread is dedicated to Shiny package - a  RStudio-curated tool for developing and deploying Interactive Data Visualization and Analysis tools and applications.

## Resources

Kick start to Shiny - https://www.datacamp.com/courses/building-web-applications-in-r-with-shiny

See also:

Shiny - Gallery (rstudio.com) - https://shiny.rstudio.com/gallery/
https://engineering-shiny.org/



# Interactive Outputs in R: plotly, Datatable, reactable

This  discussion is dedicated to tools to generate interactive graphs, tables, and other content without Shiny (which, as you know, requires a server to host your Shiny application and which for this reason cannot be easily shared with your clients, e.g. by email)



Here are the most popular ones:


https://rstudio.github.io/DT/  
https://plotly.com/r/ and   
https://glin.github.io/reactable  


## `reactable`
<!-- Your clients will love it -  -->

Check what kind of interactive coloured tables you can make with it: 
<!-- - it's like a coloured table inside your R generated report): -->
  https://glin.github.io/reactable/articles/womens-world-cup/womens-world-cup.html





# Geo/Spatial coding and visualization in R


## Resources

There's much effort  across many GC departments to analyze and visualize  geo-data. This discussion is the place to share your results, ideas or problems related to the problem.

 

Below is a great resource to start, which also provides a nice explanation on why R is believed to be the best language to do this kind of work. 

 
Geocomputation with R, a book on geographic data analysis, visualization and modeling.


The online version of the book is hosted at https://geocompr.robinlovelace.net and kept up-to-date by GitHub Actions

 
## Federal Geospatial Platform

From https://gcconnex.gc.ca/discussion/view/84695812/data-federation-federation-des-donnees

 

Yukon’s open geospatial data is now searchable on the Federal Geospatial Platform (FGP) (https://gcgeo.gc.ca/) and on Government of Canada Open Maps Portal. Check it out !

 

With the addition of Yukon's resources, the FGP now offers over 5,000 datasets available to discover and download, for public servants and Canadians, all in one location.

 

Wondering how to create a map with your data? We can help you do so, from A to Z, at no cost. Contact us at nrcan.geoinfo.rncan@canada.ca

 
## Tutorials 
 
Check codes and notes for the two Tutorials that we had on this subject this summer:
 
https://gccode.ssc-spc.gc.ca/r4gc/resources/introSpatialAnalysis
 
 
## Dealing with memory issues

A blog post that illustrates a few ways to avoid overloading R's memory when working with large spatial objects (here's looking at you, 30-m land cover map of North America!).


https://www.ecologi.st/post/big-spatial-data/

 

The two other posts on that blog also have some really nice tips for general R coding. 


## Canadian geo-data

Useful code and R packages from public domain to work with Canadian geo-data. 

From https://mountainmath.ca
- https://github.com/mountainMath/mountainmathHelpers
- tongfen: Convenience functions for making data on different geometries, especially Canadian census geometries, comparable.
- cancensus : R wrapper for calling CensusMapper APIs
- cansim: Wrapper to access CANSIM data
- CanCovidData: Collection of data import and processing functions focused on Canadian data






# Using R with GC data infastructure (gcdocs, AWS, etc)


## gcdocs

Q:

I'm wondering if anyone has had any success accessing data from GCDocs in your respective departments ? I believe that GCDocs is implemented across most (if not all) departments so wondering if there are any existing solutions to read/write data from it.



Also wondering about whether any of you have had any luck accessing Microsoft 365 via R as well? I've had success with Microsoft365R package (https://github.com/Azure/Microsoft365R) from a personal point of view but it doesn't play well with business accounts.


<!-- A: -->
<!--   I tried using the Microsoft365R package to access my departmental (ECCC) email without success. When I tried to access it, a window popped up allowing me to request access authorization so I clicked the "Submit" (or whatever) button. That was weeks ago. Never heard anything more about it. -->

<!-- After trying many ways and weeks, I found this is NOT possible. -  It runs internal code on gcdoc end  that validates that you have right to access it and then, if you do, it also logs your action within the document's "Audit" attribute.  -->
<!-- So we still have to always make a local copy of the data (manually!), and only then we can process it from R. -->



