



# Record Linking and other Data Engineering tasks in R


## demo

See http://rcanada.shinyapps.io/demo and the #GCData2021 Data Engineering workshop  presentation - 
for the backgrounder and the demonstration of various DE tasks and solutions.

# Geo/Spatial coding and visualization in R


## Resources

There's much effort  across many GC departments to analyze and visualize  geo-data. This discussion is the place to share your results, ideas or problems related to the problem.

 

Below is a great resource to start, which also provides a nice explanation on why R is believed to be the best language to do this kind of work. 

 
Geocomputation with R, a book on geographic data analysis, visualization and modeling.


The online version of the book is hosted at https://geocompr.robinlovelace.net and kept up-to-date by GitHub Actions

 
## Federal Geospatial Platform

From https://gcconnex.gc.ca/discussion/view/84695812/data-federation-federation-des-donnees

 

Yukon’s open geospatial data is now searchable on the Federal Geospatial Platform (FGP) (https://gcgeo.gc.ca/) and on Government of Canada Open Maps Portal. Check it out !

 

With the addition of Yukon's resources, the FGP now offers over 5,000 datasets available to discover and download, for public servants and Canadians, all in one location.

 

Wondering how to create a map with your data? We can help you do so, from A to Z, at no cost. Contact us at nrcan.geoinfo.rncan@canada.ca

 
## Tutorials 
 
Check codes and notes for the two Tutorials that we had on this subject this summer:
 
https://gccode.ssc-spc.gc.ca/r4gc/resources/introSpatialAnalysis
 
 
## Dealing with memory issues

A blog post that illustrates a few ways to avoid overloading R's memory when working with large spatial objects (here's looking at you, 30-m land cover map of North America!).


https://www.ecologi.st/post/big-spatial-data/

 

The two other posts on that blog also have some really nice tips for general R coding. 


## Canadian geo-data

Useful code and R packages from public domain to work with Canadian geo-data. 

From https://mountainmath.ca
- https://github.com/mountainMath/mountainmathHelpers
- tongfen: Convenience functions for making data on different geometries, especially Canadian census geometries, comparable.
- cancensus : R wrapper for calling CensusMapper APIs
- cansim: Wrapper to access CANSIM data
- CanCovidData: Collection of data import and processing functions focused on Canadian data




<!------------------------------------------------>


# Text Analysis in R

https://gccollab.ca/discussion/view/7404441/text-analysis-in-r

## Open source textbook

https://smltar.com/ 
https://www.tidytextmining.com/
https://slcladal.github.io/topicmodels.html, https://slcladal.github.io/textanalysis.html
 
Also, a list of related resources and codes for text mining (including Web Scraping)  are collected here: https://github.com/gorodnichy/LA-R-text


## Plagiarism detection

Q:  Any ideas/packages/resources (in R) for plagiarism detection? 

 
A: 
A good  place to start is the "stylo" package (https://github.com/computationalstylistics/stylo - R package for stylometric analyses) which implements a wide variety of recent research in computational stylistics. Plagiarism detection is fraught (insert all of the usual ethical and computational caveats...), but stylo can help you identify passages that are stylistically unusual compared to the rest of the text. Unusualness definitely isn't a proxy for plagiarism, but it's a good place to start.

 
Q: 
Is this focused on English language text? Are there lexicons or libraries for comparison within other languages (e.g., French)?

A: Stylo works well with quite a few non-English languages. French, for example, is supported, as are a number of languages with non-Latin alphabets like Arabic and Korean.




## results from International Methodology Symposium

Two presentations  at [International Methodology Symposium](https://www.statcan.gc.ca/en/conferences/symposium2021/program) were about Text Analysis with R, with great ideas from both:
 

11B-4 by Andrew Stelmach from StatCan: used  `library(fastText)` -  a very powerful package from facebook AI team for  efficient learning of word representations and sentence classification. 

 

11B-2 by Dave Campbell from Carleton U:  used the  approach  that we discussed at L&L on October 9 (based on bag of words cosine distance / correlation) for matching beer products description  - https://gccode.ssc-spc.gc.ca/r4gc/resources/text/),  but addtionally applied SVD (singular value decomposition) to reduce comparison to  the most imporant words, thus reducing significantly the dimension and speed.

 

You can  find their decks here: https://drive.google.com/drive/folders/1TfuNmG3V8IEKDNNTcMZz7_YCKgqVVBju 



# Machine Learning and Modeling in R


## Resources

Below are most popular textbooks for Machine Learning and Modeling in R.  
Also see Discussion on Text Mining (https://smltar.com/ and https://www.tidytextmining.com/)
 

This one is used in many University Machine Learning courses (e.g. in University of Arizona and many others in USA):

An Introduction to Statistical Learning with Applications in R

https://www.statlearning.com/ ( https://web.stanford.edu/~hastie/ISLR2/ISLRv2_website.pdf )

 

 

These are on Tidy models (most come with source codes): https://www.tidymodels.org/books/

https://www.tmwr.org/  - TIDY MODELS WITH R

https://bookdown.org/max/FES - Feature Engineering & Selection

https://moderndive.com/. Statistical Inference via Data Science

 


## Additional references

References

- https://www.cs.huji.ac.il/~shais/UnderstandingMachineLearning/understanding-machine-learning-theory-algorithms.pdf


-http://www2.math.uu.se/~thulin/mm/breiman.pdf





# Deep Learning and Computer vision 

<!-- with Tensorflow and Keras -->

This discussion thread on Deep Learning with Tensorflow and Keras inR (https://tensorflow.rstudio.com/)


<!-- A collection of tested codes and tutorials is here: -->


Learn and Apply Artificial Neural Networks (aka Deep Learning) with Keras/Tensorflow in R/RStudio, 
Using complete prewritten codes, your own data, and data.table package:

https://github.com/gorodnichy/LA-R-KerasNN


#### Deep Learning using the h2o package in R

https://github.com/h2oai/Deep-Learning-with-h2o-in-R




# Simulation and Optimization

There are a number of R packages developed for complex processes simulations and  optimization problems, including   simulation of queueing processes and resource or performance optimization problems


They were used in the research on predicting and optimizing Border Wait Time at Canadian border.
The codes for it and the research article are available at GCcode (search "border") or by contacting [Dmitry Gorodnichy](index.html#contact).




