



# Lunch and Learn notes

These are the draft notes from  the Lunch and Learn 'Data Science with R' series organized by  R4GC community. 
Please see [Lunch and Learn](index.html#lunch-and-learn-meetups) page for details on how to join these meetings.

For video-recordings and additional notes, please join [Lunch and Learn 'Data Science with R' GCcollab group](https://gccollab.ca/groups/about/7855030) 



### Interactive Outputs in R without Shiny {-}

26 Nov 2021 - 
This meeting will be dedicated to tools to generate interactive graphs, tables, and other content without Shiny (which, as you know, requires a server to host your Shiny application and which for this reason cannot be easily shared with your clients, e.g. by email)


Here are the most popular ones:

https://rstudio.github.io/DT/ 
https://plotly.com/r/ and 
https://glin.github.io/reactable.
Many worked with plotly and DT, but reactable is another great package, which will make your outputs loved by your clients. 

12 Nov - 19 Nov 2021: 
Text Analysis with R follow-up / Converting codes to Shiny App

8 Oct 2021: 
Text Analysis with R. Part 1: identifying near-duplicate documents

1 Oct 2021: 
Shiny App to summarize very large, high-dimensional tables (code & app provided)

30 Jul - 17 Sep 2021: 
Geo/Spatial coding and visualization with R. (code provided)

16 Jul 2021: 
Dual Coding - Python and R unite ! (code provided)

9 Jul 2021: 
Exploring ggplots (recording, code provided)

2 Jul 2021: 
Parsing GC Tables (code provided)



25 Jun 2021: 
Using the Open Government Portal API within R (recording, code on github.com/open-canada)

21 Apr 2021: 
Analyzing PSES results using R and Shiny

16 Apr - 15 May 2021: 
Building R packages (recording, codes provided)




## Geo/Spatial coding and visualization with R. Part 1:

Contributed by: 

## Text Analysis with R. Part 1: 

Contributed by: 

## Dual Coding - Python and R unite !

Contributed by: 

## Working with ggtables

Contributed by: 

## Automate common look and feel of your ggplot graphs

Contributed by: 

## Automated generation of report cards

Contributed by: 



## Discussed  RStudio Webinars

Webinars at RStudio - https://www.rstudio.com/resources/webinars/ (codes at https://github.com/rstudio/webinars)
The new insights from these webinars and other R-related blogs and events are discussed at R4GC community meetups



<!-- # (PART) Q & A -->


<!-- # (APPENDIX) Appendix {-} -->

<!-- ##  Video recordings -->

